import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import { Inter } from "next/font/google";
import SideBar from "./componenets/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PPM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          style={{ height: '10000 px' }}
          className="flex flex-column flex-shrink-0"
        >
          <div className="row">
            <div className="col-3 p-0">
              <SideBar></SideBar>
            </div>
            <div className="bg-light col-9">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
